# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8b3ef10867d16241c7249f05706d6bf7ed7e8e4509f3b93cb408ae423d189dee86da399025e13ab3617a19c0d98084d2706917327fb1ee89accde6358dcc01a

test:
  secret_key_base: 927b7aa3b158b518640ad6ef1df6b7d6682de6d68f5c03f598e4ad1f753aa64a5bd41a6f79a5c5fb825d63d726bd5f7e7d545c096b38146fd527e0947960fe32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
